trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo "Do the build"
- stage: DevDeploy
  jobs:
  - deployment: DevDeployJob
    environment: Dev # Will be registered under "Azure Devops -> Environments"
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to Dev
- stage: QADeploy
  jobs:
  - deployment: QADeployJob
    environment: QA # Will be registered under "Azure Devops -> Environments"
                    # Here APPROVARS and CHECKS can be configured
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to QA
